id = "blade"
name = "Blade"
description = "Laravel Blade templating language support."
version = "0.2.2"
schema_version = 1
authors = ["Raunak Raj <bajrangcoders@gmail.com>"]
repository = "https://github.com/bajrangCoder/zed-laravel-blade"

[grammars.blade]
repository = "https://github.com/EmranMR/tree-sitter-blade"
commit = "cc764dadcbbceb3f259396fef66f970c72e94f96"

[grammars.php_only]
repository = "https://github.com/tree-sitter/tree-sitter-php"
commit = "b2278dbac9d58b02653fe6a8530ccebc492e4ed4"
path = "php_only"

[language_servers.emmet]
name = "Emmet Language Server"
language = "Blade"

[language_servers.intelephense]
name = "Intelephense"
language = "Blade"
language_ids = { Blade = "blade" }

[language_servers.phptools]
name = "PhpTools"
language = "Blade"
language_ids = { Blade = "blade" }

[language_servers.phpactor]
name = "Phpactor"
language = "Blade"
