id = "blade"
name = "Blade"
description = "Laravel Blade templating language support."
version = "0.1.0"
schema_version = 1
authors = ["Raunak Raj <bajrangcoders@gmail.com>"]
repository = "https://github.com/bajrangCoder/zed-laravel-blade"

[grammars.blade]
repository = "https://github.com/EmranMR/tree-sitter-blade"
commit = "bcdc4b01827cac21205f7453e9be02f906943128"

[grammars.php_only]
repository = "https://github.com/tree-sitter/tree-sitter-php"
commit = "f7cf7348737d8cff1b13407a0bfedce02ee7b046"
path = "php_only"

[language_servers.emmet-language-server]
name = "Emmet Language Server"
language = "Blade"

[language_servers.emmet-language-server.language_ids]
"Blade" = "blade"
